"""Added category to posts

Revision ID: 413e61a1d568
Revises: 
Create Date: 2026-02-10 02:38:20.782301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413e61a1d568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False, server_default='General'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
